
    <nav>
        <div class="leftNav navBlock">
            <a href="./index.html">
                <image src="./images/logo-black.png" id="logo"></image>
            </a>
            <ul class="navHead">
                <li>
                    <a href="./jobs.php">Job</a>
                </li>
                <li>
                    <a href="./apply.php">Apply</a>
                </li>
                <li>
                    <a href="./about.php">About</a>
                </li>
                <li>
                    <a href="./enhancement.php">Enhancement</a>
                </li>
            </ul>
            </div>
        <div class="rightNav navBlock">
            <a href="./apply.html" class="fakeBtn">
                APPLY NOW
            </a>
        </div>
    </nav> 
